version: '3.8'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    # 自動起動
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    volumes:
      # コンテナからデータを引っ張る用のフォルダ
      - 'D:\GoogleDrive\Prj\Redmine\data:/share'
      # データ本体 GoogleDriveでバックアップ
      - 'D:\GoogleDrive\Prj\Redmine\data\mariadb:/bitnami/mariadb'
      
  redmine:
    image: docker.io/bitnami/redmine:4.2.5
    # 自動起動
    restart: always
    environment:
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8888:3000'
    volumes:
      # コンテナからデータを引っ張る用のフォルダ
      - 'D:\GoogleDrive\Prj\Redmine\data:/share'
      # データ本体 GoogleDriveでバックアップ
      - 'D:\GoogleDrive\Prj\Redmine\data\themes:/opt/bitnami/redmine/public/themes'
      - 'D:\GoogleDrive\Prj\Redmine\data\db:/opt/bitnami/redmine/public/db'
      - 'D:\GoogleDrive\Prj\Redmine\data\files:/opt/bitnami/redmine/public/files'
      - 'D:\GoogleDrive\Prj\Redmine\data\plugins:/opt/bitnami/redmine/public/plugins'

    depends_on:
      - mariadb
    tty:
      true
