version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
    volumes:
      - 'mariadb_data:/bitnami'
  redmine:
    image: docker.io/bitnami/redmine:4.2.5
    environment:
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8888:3000'
    volumes:
      - 'redmine_data:/bitnami'
      - 'bitnami_data:/opt/bitnami'
    depends_on:
      - mariadb
    tty:
      true
      
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
  bitnami_data:
    driver: local